import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DarkThemeProvider from "@/src/components/DarkThemeProvider";
import ThemeScript from "@/src/components/ThemeScript";



export const metadata: Metadata = {
  title: "Ravi portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body
        className={`antialiased`}
      >
        <DarkThemeProvider>
          {children}
        </DarkThemeProvider>
      </body>
    </html>
  );
}
